# Generated by Django 5.2.7 on 2025-10-28 00:46

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="perfil",
            name="avatar",
            field=models.ImageField(
                blank=True,
                default="default/default.png",
                null=True,
                upload_to=accounts.models.avatar_upload_to,
            ),
        ),
    ]
