# Generated by Django 5.2.7 on 2025-10-28 00:50

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_perfil_avatar"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="perfil",
            options={"verbose_name": "Perfil", "verbose_name_plural": "Perfiles"},
        ),
        migrations.AlterField(
            model_name="perfil",
            name="avatar",
            field=models.ImageField(
                blank=True,
                default="default/perfil/default.png",
                null=True,
                upload_to=accounts.models.avatar_upload_to,
                verbose_name="Avatar",
            ),
        ),
    ]
