# Generated by Django 5.2.7 on 2025-10-27 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Estudiante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("apellido", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("nro_legajo", models.IntegerField(unique=True)),
                ("fecha_de_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_de_nacimiento", models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Examenes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nota", models.FloatField()),
                ("asignatura", models.CharField(max_length=30)),
                ("nombre_de_estudiante", models.CharField(max_length=100)),
            ],
        ),
    ]
