# Generated by Django 5.2.7 on 2025-10-14 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("coder", "0002_examenes"),
    ]

    operations = [
        migrations.RenameField(
            model_name="estudiante",
            old_name="fehca_de_nacimiento",
            new_name="fecha_de_nacimiento",
        ),
    ]
